# Generated by Django 5.0.3 on 2024-07-22 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="architecture_reviewer",
            new_name="architect_reviewer",
        ),
    ]
