# Generated by Django 5.0.3 on 2024-05-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_value',
            new_name='s_project_value',
        ),
    ]
