# Generated by Django 5.0.3 on 2024-05-19 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_first_payment_project_s_first_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='_autocad',
            new_name='f_autocad',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='_civil_defense',
            new_name='f_civil_defense',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='_client_form',
            new_name='f_client_form',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='_container_contract',
            new_name='f_container_contract',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='_contract',
            new_name='f_contract',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='_coordinate_certificate',
            new_name='f_coordinate_certificate',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='_deed',
            new_name='f_deed',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='_demolition_letters',
            new_name='f_demolition_letters',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='_identity',
            new_name='f_identity',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='_land_survey',
            new_name='f_land_survey',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='_license',
            new_name='f_license',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='_load_bearing_certificate',
            new_name='f_load_bearing_certificate',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='_location_certificate',
            new_name='f_location_certificate',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='_old_license',
            new_name='f_old_license',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='_plan',
            new_name='f_plan',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='_report',
            new_name='f_report',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='_soil_test',
            new_name='f_soil_test',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='_technical_report',
            new_name='f_technical_report',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='_water_authority',
            new_name='f_water_authority',
        ),
    ]
