# Generated by Django 5.0.3 on 2024-07-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_project_s_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="s_payments",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
