# Generated by Django 5.0.3 on 2024-07-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_project_s_payments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baladyproject",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="project",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="project",
            name="previous_stage",
        ),
        migrations.AddField(
            model_name="baladyproject",
            name="s_history",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
