# Generated by Django 5.0.3 on 2024-08-03 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_baladyproject_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="current_stage",
            new_name="stage",
        ),
    ]
