# Generated by Django 5.0.3 on 2024-05-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('destruction', 'Destruction'), ('restoration', 'Restoration'), ('add_floors', 'Addfloors'), ('addition', 'Addition'), ('new', 'New')], max_length=100, null=True),
        ),
    ]
