# Generated by Django 5.0.3 on 2024-08-03 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_current_stage_project_stage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baladyproject",
            old_name="path",
            new_name="stage",
        ),
        migrations.RemoveField(
            model_name="baladyproject",
            name="design_proj",
        ),
    ]
