# Generated by Django 5.0.3 on 2024-05-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='use_type',
            field=models.CharField(blank=True, choices=[('entertaining', 'Entertaining'), ('agricultural', 'Agricultural'), ('residential_commercial', 'Residentialcommercial'), ('commercial', 'Commercial'), ('residential', 'Residential')], max_length=100, null=True),
        ),
    ]
