# Generated by Django 5.0.3 on 2024-06-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_project_use_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='written_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='moved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
