# Generated by Django 5.0.3 on 2024-08-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_baladyproject_s_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="baladyproject",
            name="s_project_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
