# Generated by Django 5.0.3 on 2024-08-03 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_baladyproject_s_project_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("date", models.DateField()),
                ("stage", models.CharField(max_length=100)),
                ("s_history", models.JSONField(blank=True, default=list, null=True)),
                (
                    "paid_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.globalid"
                    ),
                ),
            ],
        ),
    ]
