# Generated by Django 5.0.3 on 2024-06-06 02:25

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_stage_project_current_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='f_autocad',
        ),
        migrations.RemoveField(
            model_name='project',
            name='f_civil_defense',
        ),
        migrations.RemoveField(
            model_name='project',
            name='f_client_form',
        ),
        migrations.RemoveField(
            model_name='project',
            name='f_container_contract',
        ),
        migrations.RemoveField(
            model_name='project',
            name='f_contract',
        ),
        migrations.RemoveField(
            model_name='project',
            name='f_coordinate_certificate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='f_deed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='f_demolition_letters',
        ),
        migrations.RemoveField(
            model_name='project',
            name='f_identity',
        ),
        migrations.RemoveField(
            model_name='project',
            name='f_land_survey',
        ),
        migrations.RemoveField(
            model_name='project',
            name='f_license',
        ),
        migrations.RemoveField(
            model_name='project',
            name='f_load_bearing_certificate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='f_location_certificate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='f_old_license',
        ),
        migrations.RemoveField(
            model_name='project',
            name='f_plan',
        ),
        migrations.RemoveField(
            model_name='project',
            name='f_report',
        ),
        migrations.RemoveField(
            model_name='project',
            name='f_soil_test',
        ),
        migrations.RemoveField(
            model_name='project',
            name='f_technical_report',
        ),
        migrations.RemoveField(
            model_name='project',
            name='f_water_authority',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('contract', 'Contract'), ('deed', 'Deed'), ('report', 'Report'), ('identity', 'Identity'), ('container_contract', 'Containercontract'), ('license', 'License'), ('plan', 'Plan'), ('load_bearing_certificate', 'Loadbearingcertificate'), ('location_certificate', 'Locationcertificate'), ('land_survey', 'Landsurvey'), ('soil_test', 'Soiltest'), ('coordinate_certificate', 'Coordinatecertificate'), ('technical_report', 'Technicalreport'), ('demolition_letters', 'Demolitionletters'), ('autocad', 'Autocad'), ('client_form', 'Clientform'), ('old_license', 'Oldlicense'), ('civil_defense', 'Civildefense'), ('water_authority', 'Waterauthority'), ('other', 'Other')], max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=api.models.PathAndRename())),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('uploaded_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.project')),
            ],
        ),
    ]
