# Generated by Django 5.0.3 on 2024-06-06 06:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_project_f_autocad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(upload_to=api.models.PathAndRename()),
        ),
    ]
