# Generated by Django 5.0.3 on 2024-08-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
