# Generated by Django 5.0.3 on 2024-06-08 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_client_id_remove_project_client_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.client'),
        ),
    ]
