# Generated by Django 5.0.3 on 2024-06-08 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_project_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_phone',
            field=models.ForeignKey(default='0565058410', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='Test Project', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('destruction', 'Destruction'), ('restoration', 'Restoration'), ('add_floors', 'Addfloors'), ('addition', 'Addition'), ('new', 'New')], default='new', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='use_type',
            field=models.CharField(choices=[('entertaining', 'Entertaining'), ('agricultural', 'Agricultural'), ('residential_commercial', 'Residentialcommercial'), ('commercial', 'Commercial'), ('residential', 'Residential')], default='residential', max_length=100),
            preserve_default=False,
        ),
    ]
