# Generated by Django 5.0.3 on 2024-08-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_baladyproject_required_attachments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="type",
            field=models.CharField(
                choices=[
                    ("deed", "Deed"),
                    ("contract", "Contract"),
                    ("report", "Report"),
                    ("identity", "Identity"),
                    ("container_contract", "Container Contract"),
                    ("license", "License"),
                    ("plan", "Plan"),
                    ("old_plan", "Old Plan"),
                    ("load_bearing_certificate", "Load Bearing Certificate"),
                    ("location_certificate", "Location Certificate"),
                    ("land_survey", "Land Survey"),
                    ("soil_test", "Soil Test"),
                    ("coordinate_certificate", "Coordinate Certificate"),
                    ("technical_report", "Technical Report"),
                    ("demolition_letters", "Demolition Letters"),
                    ("autocad", "Autocad"),
                    ("client_form", "Client Form"),
                    ("old_license", "Old License"),
                    ("civil_defense", "Civil Defense"),
                    ("water_authority", "Water Authority"),
                    ("construction_plan", "Construction Plan"),
                    ("electrical_plan", "Electrical Plan"),
                    ("energy_efficiency_plan", "Energy Efficiency Plan"),
                    ("plumbing_plan", "Plumbing Plan"),
                    ("architecture_plan", "Architecture Plan"),
                    ("building_pictures", "Building Pictures"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="baladyproject",
            name="request_type",
            field=models.JSONField(default=list, max_length=100),
        ),
    ]
