# Generated by Django 5.0.3 on 2024-08-10 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_attachment_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baladyproject",
            old_name="request_type",
            new_name="request_types",
        ),
    ]
