# Generated by Django 5.0.3 on 2024-06-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_project_current_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
