# Generated by Django 5.0.3 on 2024-08-10 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_rename_request_type_baladyproject_request_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="written_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.globalid",
            ),
        ),
    ]
