# Generated by Django 5.0.3 on 2024-08-10 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_comment_written_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="global_uploaded_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.globalid",
            ),
        ),
    ]
