# Generated by Django 5.0.3 on 2024-06-20 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='investor_affiliation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='BaladyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('request_status', models.CharField(blank=True, choices=[('Working on it', 'Working On It'), ('Done', 'Done'), ('Hold', 'Hold'), ('Not required', 'Not Required')], max_length=100, null=True)),
                ('architecture_status', models.CharField(blank=True, choices=[('Working on it', 'Working On It'), ('Done', 'Done'), ('Hold', 'Hold'), ('Not required', 'Not Required')], max_length=100, null=True)),
                ('construction_status', models.CharField(blank=True, choices=[('Working on it', 'Working On It'), ('Done', 'Done'), ('Hold', 'Hold'), ('Not required', 'Not Required')], max_length=100, null=True)),
                ('plumbing_status', models.CharField(blank=True, choices=[('Working on it', 'Working On It'), ('Done', 'Done'), ('Hold', 'Hold'), ('Not required', 'Not Required')], max_length=100, null=True)),
                ('electrical_status', models.CharField(blank=True, choices=[('Working on it', 'Working On It'), ('Done', 'Done'), ('Hold', 'Hold'), ('Not required', 'Not Required')], max_length=100, null=True)),
                ('columns_approval_date', models.DateField(blank=True, null=True)),
                ('sketch_approval_date', models.DateField(blank=True, null=True)),
                ('investor_affiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('project_receipt_date', models.DateField(blank=True, null=True)),
                ('project_type', models.CharField(blank=True, choices=[('destruction', 'Destruction'), ('restoration', 'Restoration'), ('add_floors', 'Addfloors'), ('addition', 'Addition'), ('new', 'New')], max_length=100, null=True)),
                ('land_number', models.CharField(blank=True, max_length=100, null=True)),
                ('land_area', models.FloatField(blank=True, null=True)),
                ('project_location', models.CharField(blank=True, max_length=100, null=True)),
                ('project_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sketch_progress', models.CharField(blank=True, max_length=100, null=True)),
                ('construction_start_date', models.DateField(blank=True, null=True)),
                ('construction_review', models.CharField(blank=True, max_length=255, null=True)),
                ('construction_end_date', models.DateField(blank=True, null=True)),
                ('electrical_start_date', models.DateField(blank=True, null=True)),
                ('electrical_end_date', models.DateField(blank=True, null=True)),
                ('architect_start_date', models.DateField(blank=True, null=True)),
                ('architect_end_date', models.DateField(blank=True, null=True)),
                ('plumbing_start_date', models.DateField(blank=True, null=True)),
                ('plumbing_end_date', models.DateField(blank=True, null=True)),
                ('plan_delivery_date', models.DateField(blank=True, null=True)),
                ('client_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balady_projects', to='api.client')),
                ('construction_eng', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contruction_engineer_balady', to=settings.AUTH_USER_MODEL)),
                ('design_eng', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designer_balady', to=settings.AUTH_USER_MODEL)),
                ('electrical_eng', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electrical_engineer_balady', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
