# Generated by Django 5.0.3 on 2024-08-10 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_attachment_global_uploaded_for"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="uploaded_for",
        ),
    ]
