# Generated by Django 5.0.3 on 2024-06-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_project_investor_affiliation_baladyproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='baladyproject',
            name='stage',
            field=models.CharField(choices=[('new_construction_license', 'New Construction License'), ('working_on_it', 'Working On It'), ('incomplete_or_requirements_are_unclear', 'Incomplete Or Requirements Are Unclear'), ('temporarly_stopped_or_technical_issues', 'Temporarly Stopped Or Technical Issues'), ('ready_for_pickup', 'Ready For Pickup')], default='new_construction_license', max_length=100),
            preserve_default=False,
        ),
    ]
