# Generated by Django 5.0.3 on 2024-08-10 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_remove_attachment_uploaded_for"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attachment",
            old_name="global_uploaded_for",
            new_name="uploaded_for",
        ),
    ]
