# Generated by Django 5.0.3 on 2024-06-21 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_baladyproject_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandSurveyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('land_survey', 'Land Survey'), ('land_report', 'Land Report'), ('completed_projects', 'Completed Projects'), ('informal_transactions', 'Informal Transactions')], max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('location_visit', models.CharField(blank=True, choices=[('Working on it', 'Working On It'), ('Done', 'Done'), ('Hold', 'Hold'), ('Not required', 'Not Required')], max_length=100, null=True)),
                ('location_visit_date', models.DateField(blank=True, null=True)),
                ('protocol_number', models.IntegerField(blank=True, null=True)),
                ('transaction_review', models.CharField(blank=True, max_length=255, null=True)),
                ('protocol_purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Working on it', 'Working On It'), ('Done', 'Done'), ('Hold', 'Hold'), ('Not required', 'Not Required')], max_length=100, null=True)),
                ('survey_report_issuance', models.CharField(blank=True, max_length=100, null=True)),
                ('client_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_survey_projects', to='api.client')),
            ],
        ),
    ]
