# Generated by Django 5.0.3 on 2024-06-22 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_landsurveyproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortingDeedsProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('land_sorting', 'Land Sorting'), ('land_merging', 'Land Merging'), ('housing_sorting', 'Housing Sorting'), ('land_sorting_completed', 'Land Sorting Completed'), ('land_merging_completed', 'Land Merging Completed'), ('housing_sorting_completed', 'Housing Sorting Completed')], max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('case_study', models.CharField(blank=True, max_length=100, null=True)),
                ('spatial_inspection', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_upload', models.CharField(blank=True, max_length=100, null=True)),
                ('urban_planning_review', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_bill', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('accounting', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('client_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorting_deeds_projects', to='api.client')),
            ],
        ),
    ]
