# Generated by Django 5.0.3 on 2024-08-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_qataryofficeproject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baladyproject",
            old_name="request_submission",
            new_name="request_submissions",
        ),
    ]
