# Generated by Django 5.0.3 on 2024-08-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_rename_request_submission_baladyproject_request_submissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baladyproject",
            name="request_submissions",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
