# Generated by Django 5.0.3 on 2024-08-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_alter_baladyproject_request_submissions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baladyproject",
            old_name="municipality_visit",
            new_name="municipality_visits",
        ),
    ]
