# Generated by Django 5.0.3 on 2024-08-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_rename_municipality_visit_baladyproject_municipality_visits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baladyproject",
            name="municipality_visits",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
