# Generated by Django 5.0.3 on 2024-08-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_baladyproject_municipality_visits"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Project",
            new_name="DesignProject",
        ),
        migrations.RenameField(
            model_name="landsurveyproject",
            old_name="protocol_number",
            new_name="record_number",
        ),
        migrations.RenameField(
            model_name="landsurveyproject",
            old_name="protocol_purpose",
            new_name="record_purpose",
        ),
        migrations.AlterField(
            model_name="baladyproject",
            name="stage",
            field=models.CharField(
                choices=[
                    ("balady", "Balady"),
                    ("service_card", "Service Card"),
                    ("quantity_sorting", "Quantity Sorting"),
                    ("supervision", "Supervision"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="qataryofficeproject",
            name="stage",
            field=models.CharField(
                choices=[
                    ("main", "Main"),
                    ("land_report", "Land Report"),
                    ("completed_land_survey", "Completed Land Survey"),
                    ("informal_transactions", "Informal Transactions"),
                ],
                max_length=100,
            ),
        ),
    ]
