# Generated by Django 5.0.3 on 2024-07-06 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_baladyproject_request_review_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baladyproject',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='baladyproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
