# Generated by Django 5.0.3 on 2024-07-06 08:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_baladyproject_options_baladyproject_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baladyproject',
            options={'ordering': ['moved_at']},
        ),
        migrations.AddField(
            model_name='baladyproject',
            name='moved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
