# Generated by Django 5.0.3 on 2024-08-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_alter_landsurveyproject_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landsurveyproject",
            name="s_payments",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="landsurveyproject",
            name="s_project_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="qataryofficeproject",
            name="s_payments",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="qataryofficeproject",
            name="s_project_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sortingdeedsproject",
            name="s_payments",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="sortingdeedsproject",
            name="s_project_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
