# Generated by Django 5.0.3 on 2024-07-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_remove_project_autocad_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="baladyproject",
            name="global_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="landsurveyproject",
            name="global_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="global_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sortingdeedsproject",
            name="global_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
