# Generated by Django 5.0.3 on 2024-08-20 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_alter_designproject_options_globalid_qatari_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designproject",
            name="moved_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2024, 8, 20, 14, 26, 47, 683327),
            ),
            preserve_default=False,
        ),
    ]
