# Generated by Django 5.0.3 on 2024-08-20 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_alter_designproject_moved_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qataryofficeproject",
            name="global_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.globalid",
            ),
        ),
    ]
