# Generated by Django 5.0.3 on 2024-07-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_baladyproject_global_id_landsurveyproject_global_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="history",
            new_name="s_history",
        ),
        migrations.RemoveField(
            model_name="project",
            name="s_first_payment",
        ),
        migrations.RemoveField(
            model_name="project",
            name="s_first_payment_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="s_first_payment_stage",
        ),
        migrations.RemoveField(
            model_name="project",
            name="s_second_payment",
        ),
        migrations.RemoveField(
            model_name="project",
            name="s_second_payment_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="s_second_payment_stage",
        ),
        migrations.RemoveField(
            model_name="project",
            name="s_third_payment",
        ),
        migrations.RemoveField(
            model_name="project",
            name="s_third_payment_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="s_third_payment_stage",
        ),
        migrations.AddField(
            model_name="project",
            name="s_payments",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
