# Generated by Django 5.0.3 on 2024-07-21 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_rename_history_project_s_history_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="plumbin_stop_reason",
            new_name="plumbing_stop_reason",
        ),
    ]
