# Generated by Django 5.0.3 on 2024-08-20 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_landsurveyproject_required_attachments_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QataryOfficeProject",
            new_name="QatariOfficeProject",
        ),
    ]
