# Generated by Django 5.0.3 on 2024-08-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_alter_designproject_stage_alter_tableview_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baladyproject",
            name="stage",
            field=models.CharField(
                choices=[
                    ("balady", "Balady"),
                    ("service_card", "Service Card"),
                    ("quantity_sorting", "Quantity Sorting"),
                    ("supervision", "Supervision"),
                    ("deleted_projects", "Deleted Projects"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="designproject",
            name="stage",
            field=models.CharField(
                choices=[
                    ("reception", "Reception"),
                    ("sketch", "Sketch"),
                    ("sketch_review", "Sketch Review"),
                    ("approval_before_columns", "Approval Before Columns"),
                    ("awaiting_client_approval", "Awaiting Client Approval"),
                    ("execution_stage", "Execution Stage"),
                    ("autocad_review", "Autocad Review"),
                    ("ready_to_print", "Ready To Print"),
                    ("validate_sign_review_copy", "Validate Sign Review Copy"),
                    ("ready_to_collect", "Ready To Collect"),
                    ("client_received_copy", "Client Received Copy"),
                    ("edit_client_notes", "Edit Client Notes"),
                    ("license_issuance", "License Issuance"),
                    ("ready_for_final_receipt", "Ready For Final Receipt"),
                    ("completed_projects", "Completed Projects"),
                    ("inactive_projects", "Inactive Projects"),
                    ("deleted_projects", "Deleted Projects"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="landsurveyproject",
            name="stage",
            field=models.CharField(
                choices=[
                    ("land_survey", "Land Survey"),
                    ("land_report", "Land Report"),
                    ("completed_projects", "Completed Projects"),
                    ("informal_transactions", "Informal Transactions"),
                    ("deleted_projects", "Deleted Projects"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="qatariofficeproject",
            name="stage",
            field=models.CharField(
                choices=[
                    ("main", "Main"),
                    ("land_report", "Land Report"),
                    ("completed_land_survey", "Completed Land Survey"),
                    ("informal_transactions", "Informal Transactions"),
                    ("deleted_projects", "Deleted Projects"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="sortingdeedsproject",
            name="stage",
            field=models.CharField(
                choices=[
                    ("land_sorting", "Land Sorting"),
                    ("land_merging", "Land Merging"),
                    ("housing_sorting", "Housing Sorting"),
                    ("completed_land_sorting", "Completed Land Sorting"),
                    ("completed_land_merging", "Completed Land Merging"),
                    ("completed_housing_sorting", "Completed Housing Sorting"),
                    ("deleted_projects", "Deleted Projects"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="tableview",
            name="stage",
            field=models.CharField(
                choices=[
                    ("reception", "Reception"),
                    ("sketch", "Sketch"),
                    ("sketch_review", "Sketch Review"),
                    ("approval_before_columns", "Approval Before Columns"),
                    ("awaiting_client_approval", "Awaiting Client Approval"),
                    ("execution_stage", "Execution Stage"),
                    ("autocad_review", "Autocad Review"),
                    ("ready_to_print", "Ready To Print"),
                    ("validate_sign_review_copy", "Validate Sign Review Copy"),
                    ("ready_to_collect", "Ready To Collect"),
                    ("client_received_copy", "Client Received Copy"),
                    ("edit_client_notes", "Edit Client Notes"),
                    ("license_issuance", "License Issuance"),
                    ("ready_for_final_receipt", "Ready For Final Receipt"),
                    ("completed_projects", "Completed Projects"),
                    ("inactive_projects", "Inactive Projects"),
                    ("deleted_projects", "Deleted Projects"),
                ],
                max_length=100,
            ),
        ),
    ]
