# Generated by Django 5.0.3 on 2024-09-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_baladyproject_supervisor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="title",
        ),
        migrations.AddField(
            model_name="attachment",
            name="note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
