# Generated by Django 5.0.3 on 2024-09-11 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_remove_attachment_title_attachment_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="baladyproject",
            name="record_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="landsurveyproject",
            name="record_number",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ProvisionProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("main", "Main"),
                            ("visit_supervision", "Visit Supervision"),
                            ("completed_projects", "Completed Projects"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "use_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entertaining", "Entertaining"),
                            ("agricultural", "Agricultural"),
                            ("residential_commercial", "Residentialcommercial"),
                            ("commercial", "Commercial"),
                            ("residential", "Residential"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "supervision_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("indoor_contract", "Indoor Contract"),
                            ("outdoor_contract", "Outdoor Contract"),
                            ("indoor_visits", "Indoor Visits"),
                            ("outdoor_visits", "Outdoor Visits"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("contract_date", models.DateField(blank=True, null=True)),
                (
                    "land_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "plan_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "project_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("floors_number", models.SmallIntegerField(blank=True, null=True)),
                ("visits", models.JSONField(blank=True, default=list, null=True)),
                (
                    "investor_affiliation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("moved_at", models.DateTimeField(auto_now_add=True)),
                ("s_project_value", models.FloatField(blank=True, null=True)),
                ("s_payments", models.JSONField(default=list)),
                (
                    "client_phone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provision_projects",
                        to="api.client",
                    ),
                ),
                (
                    "global_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.globalid",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provision_supervisor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-moved_at"],
            },
        ),
        migrations.AddField(
            model_name="globalid",
            name="provision",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.provisionproject",
            ),
        ),
    ]
