# Generated by Django 5.0.3 on 2024-09-11 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_rename_provisionproject_supervisionproject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supervisionproject",
            options={"ordering": ["moved_at"]},
        ),
    ]
