# Generated by Django 5.0.3 on 2024-09-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_alter_supervisionproject_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supervisionproject",
            name="stage",
            field=models.CharField(
                choices=[
                    ("main", "Main"),
                    ("visit_supervision", "Visit Supervision"),
                    ("completed_supervision", "Completed Supervision"),
                ],
                max_length=100,
            ),
        ),
    ]
