# Generated by Django 5.0.3 on 2024-09-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_rename_qatariofficeproject_qatariproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="supervisionproject",
            name="required_attachments",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
