# Generated by Django 5.0.3 on 2024-09-11 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_rename_provision_globalid_supervision"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "visit_purpose",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("note", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="visits_attachments/"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
