# Generated by Django 5.0.3 on 2024-09-12 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_visit_visited_for"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visit",
            old_name="visit_purpose",
            new_name="purpose",
        ),
    ]
