# Generated by Django 5.0.3 on 2024-09-12 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_rename_visit_purpose_visit_purpose"),
    ]

    operations = [
        migrations.RenameField(
            model_name="history",
            old_name="stage",
            new_name="previous_stage",
        ),
        migrations.RemoveField(
            model_name="history",
            name="by",
        ),
        migrations.AddField(
            model_name="history",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="api.globalid",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
