# Generated by Django 5.0.3 on 2024-09-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_alter_employee_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baladyproject",
            old_name="deleted_from",
            new_name="delete_stage",
        ),
        migrations.RenameField(
            model_name="designproject",
            old_name="deleted_from",
            new_name="delete_stage",
        ),
        migrations.RenameField(
            model_name="landsurveyproject",
            old_name="deleted_from",
            new_name="delete_stage",
        ),
        migrations.RenameField(
            model_name="qatariproject",
            old_name="deleted_from",
            new_name="delete_stage",
        ),
        migrations.RenameField(
            model_name="sortingdeedsproject",
            old_name="deleted_from",
            new_name="delete_stage",
        ),
        migrations.RenameField(
            model_name="supervisionproject",
            old_name="deleted_from",
            new_name="delete_stage",
        ),
    ]
