# Generated by Django 5.0.3 on 2024-09-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_supervisionproject_delete_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baladyproject',
            name='delete_stage',
            field=models.CharField(blank=True, choices=[('balady', 'Balady'), ('completed_balady', 'Completed Balady'), ('service_card', 'Service Card'), ('completed_service_card', 'Completed Service Card'), ('quantity_sorting', 'Quantity Sorting'), ('completed_quantity_sorting', 'Completed Quantity Sorting'), ('deleted_projects', 'Deleted Projects')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baladyproject',
            name='stage',
            field=models.CharField(choices=[('balady', 'Balady'), ('completed_balady', 'Completed Balady'), ('service_card', 'Service Card'), ('completed_service_card', 'Completed Service Card'), ('quantity_sorting', 'Quantity Sorting'), ('completed_quantity_sorting', 'Completed Quantity Sorting'), ('deleted_projects', 'Deleted Projects')], max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/comments/'),
        ),
        migrations.AlterField(
            model_name='landsurveyproject',
            name='delete_stage',
            field=models.CharField(blank=True, choices=[('land_survey', 'Land Survey'), ('completed_land_survey', 'Completed Land Survey'), ('land_report', 'Land Report'), ('completed_land_report', 'Completed Land Report'), ('informal_transactions', 'Informal Transactions'), ('completed_informal_transactions', 'Completed Informal Transactions'), ('deleted_projects', 'Deleted Projects')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='landsurveyproject',
            name='stage',
            field=models.CharField(choices=[('land_survey', 'Land Survey'), ('completed_land_survey', 'Completed Land Survey'), ('land_report', 'Land Report'), ('completed_land_report', 'Completed Land Report'), ('informal_transactions', 'Informal Transactions'), ('completed_informal_transactions', 'Completed Informal Transactions'), ('deleted_projects', 'Deleted Projects')], max_length=100),
        ),
    ]
