# Generated by Django 5.0.3 on 2024-10-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0062_designproject_project_submission_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baladyproject",
            name="delete_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("balady", "Balady"),
                    ("completed_balady", "Completed Balady"),
                    ("stopped_balady", "Stopped Balady"),
                    ("service_card", "Service Card"),
                    ("completed_service_card", "Completed Service Card"),
                    ("quantity_sorting", "Quantity Sorting"),
                    ("completed_quantity_sorting", "Completed Quantity Sorting"),
                    ("deleted_projects", "Deleted Projects"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="baladyproject",
            name="stage",
            field=models.CharField(
                choices=[
                    ("balady", "Balady"),
                    ("completed_balady", "Completed Balady"),
                    ("stopped_balady", "Stopped Balady"),
                    ("service_card", "Service Card"),
                    ("completed_service_card", "Completed Service Card"),
                    ("quantity_sorting", "Quantity Sorting"),
                    ("completed_quantity_sorting", "Completed Quantity Sorting"),
                    ("deleted_projects", "Deleted Projects"),
                ],
                max_length=100,
            ),
        ),
    ]
