# Generated by Django 5.0.3 on 2024-10-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0063_alter_baladyproject_delete_stage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="baladyproject",
            name="submission_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baladyproject",
            name="upload_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
