ATTACHMENT_TEMPLATES = {
    "design": {
        "new": {
            "entertaining": [
                "contract",
                "deed",
                "identity",
                "land_survey",
                "client_form",
                "architecture_plan",
                "construction_plan",
                "plumbing_plan",
                "electrical_plan",
                "energy_efficiency_plan",
                "soil_test",
            ],
            "agricultural": [
                "contract",
                "deed",
                "identity",
                "land_survey",
                "client_form",
                "architecture_plan",
                "construction_plan",
                "plumbing_plan",
                "electrical_plan",
                "energy_efficiency_plan",
                "soil_test",
            ],
            "residential_commercial": [
                "contract",
                "deed",
                "identity",
                "land_survey",
                "client_form",
                "architecture_plan",
                "construction_plan",
                "plumbing_plan",
                "electrical_plan",
                "energy_efficiency_plan",
                "soil_test",
                "civil_defense",
            ],
            "residential": [
                "contract",
                "deed",
                "identity",
                "land_survey",
                "client_form",
                "architecture_plan",
                "construction_plan",
                "plumbing_plan",
                "electrical_plan",
                "energy_efficiency_plan",
                "soil_test",
            ],
        },
        "addition": {
            "entertaining": [
                "contract",
                "deed",
                "identity",
                "land_survey",
                "client_form",
                "architecture_plan",
                "construction_plan",
                "plumbing_plan",
                "electrical_plan",
                "energy_efficiency_plan",
                "old_license",
                "plan",
                "building_pictures",
            ],
            "agricultural": [
                "contract",
                "deed",
                "identity",
                "land_survey",
                "client_form",
                "architecture_plan",
                "construction_plan",
                "plumbing_plan",
                "electrical_plan",
                "energy_efficiency_plan",
                "old_license",
                "plan",
                "building_pictures",
            ],
            "residential_commercial": [
                "contract",
                "deed",
                "identity",
                "land_survey",
                "client_form",
                "architecture_plan",
                "construction_plan",
                "plumbing_plan",
                "electrical_plan",
                "energy_efficiency_plan",
                "old_license",
                "plan",
                "building_pictures",
            ],
            "residential": [
                "contract",
                "deed",
                "identity",
                "land_survey",
                "client_form",
                "architecture_plan",
                "construction_plan",
                "plumbing_plan",
                "electrical_plan",
                "energy_efficiency_plan",
                "old_license",
                "plan",
                "building_pictures",
            ],
        },
        "add_floors": {
            "entertaining": [
                "contract",
                "deed",
                "identity",
                "land_survey",
                "client_form",
                "architecture_plan",
                "construction_plan",
                "plumbing_plan",
                "electrical_plan",
                "energy_efficiency_plan",
                "old_license",
                "load_bearing_certificate",
                "plan",
                "building_pictures",
            ],
            "agricultural": [
                "contract",
                "deed",
                "identity",
                "land_survey",
                "client_form",
                "architecture_plan",
                "construction_plan",
                "plumbing_plan",
                "electrical_plan",
                "energy_efficiency_plan",
                "old_license",
                "load_bearing_certificate",
                "plan",
                "building_pictures",
            ],
            "residential_commercial": [
                "contract",
                "deed",
                "identity",
                "land_survey",
                "client_form",
                "architecture_plan",
                "construction_plan",
                "plumbing_plan",
                "electrical_plan",
                "energy_efficiency_plan",
                "old_license",
                "load_bearing_certificate",
                "plan",
                "building_pictures",
            ],
            "residential": [
                "contract",
                "deed",
                "identity",
                "land_survey",
                "client_form",
                "architecture_plan",
                "construction_plan",
                "plumbing_plan",
                "electrical_plan",
                "energy_efficiency_plan",
                "old_license",
                "load_bearing_certificate",
                "plan",
                "building_pictures",
            ],
        },
        "restoration": {
            "entertaining": [
                "contract",
                "deed",
                "identity",
                "land_survey",
                "client_form",
                "architecture_plan",
                "construction_plan",
                "plumbing_plan",
                "electrical_plan",
                "energy_efficiency_plan",
                "old_license",
                "report",
                "container_contract",
                "plan",
                "building_pictures",
            ],
            "agricultural": [
                "contract",
                "deed",
                "identity",
                "land_survey",
                "client_form",
                "architecture_plan",
                "construction_plan",
                "plumbing_plan",
                "electrical_plan",
                "energy_efficiency_plan",
                "old_license",
                "report",
                "container_contract",
                "plan",
                "building_pictures",
            ],
            "residential_commercial": [
                "contract",
                "deed",
                "identity",
                "land_survey",
                "client_form",
                "architecture_plan",
                "construction_plan",
                "plumbing_plan",
                "electrical_plan",
                "energy_efficiency_plan",
                "old_license",
                "report",
                "container_contract",
                "plan",
                "building_pictures",
            ],
            "residential": [
                "contract",
                "deed",
                "identity",
                "land_survey",
                "client_form",
                "architecture_plan",
                "construction_plan",
                "plumbing_plan",
                "electrical_plan",
                "energy_efficiency_plan",
                "old_license",
                "report",
                "container_contract",
                "plan",
                "building_pictures",
            ],
        },
        "destruction": {
            "entertaining": [
                "contract",
                "deed",
                "identity",
                "land_survey",
                "client_form",
                "architecture_plan",
                "construction_plan",
                "plumbing_plan",
                "electrical_plan",
                "energy_efficiency_plan",
                "old_license",
                "coordinate_certificate",
                "technical_report",
                "demolition_letters",
                "civil_defense",
                "water_authority",
            ],
            "agricultural": [
                "contract",
                "deed",
                "identity",
                "land_survey",
                "client_form",
                "architecture_plan",
                "construction_plan",
                "plumbing_plan",
                "electrical_plan",
                "energy_efficiency_plan",
                "old_license",
                "coordinate_certificate",
                "technical_report",
                "demolition_letters",
                "civil_defense",
                "water_authority",
            ],
            "residential_commercial": [
                "contract",
                "deed",
                "identity",
                "land_survey",
                "client_form",
                "architecture_plan",
                "construction_plan",
                "plumbing_plan",
                "electrical_plan",
                "energy_efficiency_plan",
                "old_license",
                "coordinate_certificate",
                "technical_report",
                "demolition_letters",
                "civil_defense",
                "water_authority",
            ],
            "residential": [
                "contract",
                "deed",
                "identity",
                "land_survey",
                "client_form",
                "architecture_plan",
                "construction_plan",
                "plumbing_plan",
                "electrical_plan",
                "energy_efficiency_plan",
                "old_license",
                "coordinate_certificate",
                "technical_report",
                "demolition_letters",
                "civil_defense",
                "water_authority",
            ],
        },
    },
    "balady": {
        "issue_license": {
            "administrative": [
                "land_survey",
                "approved_contractor",
                "engineering_supervision",
            ],
            "engineering": [],
        },
        "convert_license_to_electronic": {
            "administrative": [],
            "engineering": [],
        },
        "restoration_license": {
            "administrative": [],
            "engineering": [],
        },
        "add_modify_components_license": {
            "administrative": [],
            "engineering": [],
        },
        "construction_completion_certificate": {
            "administrative": [],
            "engineering": [],
        },
        "license_separation": {
            "administrative": [],
            "engineering": [],
        },
        "license_renewal": {
            "administrative": [],
            "engineering": [],
        },
        "demolition_license": {
            "administrative": [],
            "engineering": [],
        },
        "ownership_license_transfer": {
            "administrative": [],
            "engineering": [],
        },
        "survey_decision": {
            "administrative": [],
            "engineering": [],
        },
        "service_card": {
            "administrative": [],
            "engineering": [],
        },
        "loading_certificate": {
            "administrative": [],
            "engineering": [],
        },
        "components_form": {
            "administrative": [],
            "engineering": [],
        },
        "quantity_sorting": {
            "administrative": [],
            "engineering": [],
        },
    },
}
